export type Giocatore = {
  nome: string;
  categoria: string;
  ruolo: string;
};

export const ROSA: Giocatore[] = [
  // U19
  { nome: "Bagnoli Edoardo",          categoria: "U19", ruolo: "Difensore"      },
  { nome: "Barros Cabezas Ronie",     categoria: "U19", ruolo: "Centrocampista" },
  { nome: "Bernardi Andrea",          categoria: "U19", ruolo: "Attaccante"     },
  { nome: "Bighetti Paolo",           categoria: "U19", ruolo: "Attaccante"     },
  { nome: "Bignamini Filippo",        categoria: "U19", ruolo: "Difensore"      },
  { nome: "Biolchi Pietro",           categoria: "U19", ruolo: "Centrocampista" },
  { nome: "Callini Tommaso",          categoria: "U19", ruolo: "Centrocampista" },
  { nome: "Castellucchio Gabriele",   categoria: "U19", ruolo: "Difensore"      },
  { nome: "Chiesa Mattia",            categoria: "U19", ruolo: "Difensore"      },
  { nome: "Di Palma Angelo Antonio",  categoria: "U19", ruolo: "Difensore"      },
  { nome: "Ditanto Tiziano",          categoria: "U19", ruolo: "Attaccante"     },
  { nome: "Donati Pietro",            categoria: "U19", ruolo: "Centrocampista" },
  { nome: "Gazzoni Matteo",           categoria: "U19", ruolo: "Difensore"      },
  { nome: "Herzuah Gabriel",          categoria: "U19", ruolo: "Attaccante"     },
  { nome: "Invernizzi Leonardo",      categoria: "U19", ruolo: "Attaccante"     },
  { nome: "Kaba Karamoko",            categoria: "U19", ruolo: "Attaccante"     },
  { nome: "Liberali Riccardo",        categoria: "U19", ruolo: "Portiere"       },
  { nome: "Marsi Simone",             categoria: "U19", ruolo: "Difensore"      },
  { nome: "Mazzoleni Andrea",         categoria: "U19", ruolo: "Centrocampista" },
  { nome: "Murante Alessandro",       categoria: "U19", ruolo: "Centrocampista" },
  { nome: "Norelli Cristian",         categoria: "U19", ruolo: "Centrocampista" },
  { nome: "Pancini Alex",             categoria: "U19", ruolo: "Difensore"      },
  { nome: "Patitucci Christian",      categoria: "U19", ruolo: "Difensore"      },
  { nome: "Pollastri Luca",           categoria: "U19", ruolo: "Portiere"       },
  { nome: "Rosa Riccardo",            categoria: "U19", ruolo: "Centrocampista" },
  { nome: "Scocco Lionel",            categoria: "U19", ruolo: "Centrocampista" },
  { nome: "Silvestri Cristiano",      categoria: "U19", ruolo: "Centrocampista" },
  { nome: "Stefani Christian",        categoria: "U19", ruolo: "Attaccante"     },
  { nome: "Tasso Achille",            categoria: "U19", ruolo: "Centrocampista" },
  { nome: "Tumaku Niccolò",           categoria: "U19", ruolo: "Portiere"       },
  { nome: "Vigilati Tommaso",         categoria: "U19", ruolo: "Difensore"      },
  { nome: "Villa Riccardo",           categoria: "U19", ruolo: "Difensore"      },

  // U17
  { nome: "Alfa Karim",                    categoria: "U17", ruolo: "Attaccante"     },
  { nome: "Awungnkeng Adriano Asongan",    categoria: "U17", ruolo: "Centrocampista" },
  { nome: "Banes Duany Alessandro",        categoria: "U17", ruolo: "Attaccante"     },
  { nome: "Bassani Edoardo",               categoria: "U17", ruolo: "Difensore"      },
  { nome: "Bertoletti Gabriele",           categoria: "U17", ruolo: "Difensore"      },
  { nome: "Bollinella Mattia",             categoria: "U17", ruolo: "Attaccante"     },
  { nome: "Bresciani Nicholas",            categoria: "U17", ruolo: "Centrocampista" },
  { nome: "Carne Riccardo",               categoria: "U17", ruolo: "Difensore"      },
  { nome: "Chiesa Samuele",               categoria: "U17", ruolo: "Attaccante"     },
  { nome: "Ciceri Roberto",               categoria: "U17", ruolo: "Difensore"      },
  { nome: "Cingolani Raoul",              categoria: "U17", ruolo: "Portiere"       },
  { nome: "Colonna Alessandro",           categoria: "U17", ruolo: "Portiere"       },
  { nome: "Facchi Brando",                categoria: "U17", ruolo: "Difensore"      },
  { nome: "Faye Abdoul Wahab",            categoria: "U17", ruolo: "Attaccante"     },
  { nome: "Ferrario Claudio Emanuel",     categoria: "U17", ruolo: "Attaccante"     },
  { nome: "Morroi Lorenzo",               categoria: "U17", ruolo: "Centrocampista" },
  { nome: "Motoi Florin Rany",            categoria: "U17", ruolo: "Difensore"      },
  { nome: "N Gbesso Gian David",          categoria: "U17", ruolo: "Centrocampista" },
  { nome: "Pasotti Fabrizio",             categoria: "U17", ruolo: "Difensore"      },
  { nome: "Pedretti Luca",               categoria: "U17", ruolo: "Centrocampista" },
  { nome: "Restieri Alexander",           categoria: "U17", ruolo: "Attaccante"     },
  { nome: "Ronchi Lorenzo",               categoria: "U17", ruolo: "Portiere"       },
  { nome: "Tomasini Filippo",             categoria: "U17", ruolo: "Difensore"      },
  { nome: "Turra Leonardo",               categoria: "U17", ruolo: "Centrocampista" },
  { nome: "Veto Djolo Eolie Samuel",      categoria: "U17", ruolo: "Centrocampista" },
  { nome: "Vignati Christian",            categoria: "U17", ruolo: "Difensore"      },
  { nome: "Zanardelli Nicola",            categoria: "U17", ruolo: "Attaccante"     },

  // U16
  { nome: "Baron Alessandro",             categoria: "U16", ruolo: "Attaccante"     },
  { nome: "Bianchi Federico",             categoria: "U16", ruolo: "Portiere"       },
  { nome: "Bianchi Luca",                 categoria: "U16", ruolo: "Difensore"      },
  { nome: "Bocchia Romeo",                categoria: "U16", ruolo: "Difensore"      },
  { nome: "Casella Mattia",               categoria: "U16", ruolo: "Difensore"      },
  { nome: "Ceruti Antonio",               categoria: "U16", ruolo: "Difensore"      },
  { nome: "Del Campo Andrea",             categoria: "U16", ruolo: "Difensore"      },
  { nome: "Dushku Jonathan",              categoria: "U16", ruolo: "Attaccante"     },
  { nome: "Fantigrossi Matteo",           categoria: "U16", ruolo: "Attaccante"     },
  { nome: "Iapalucci Moustapha",          categoria: "U16", ruolo: "Attaccante"     },
  { nome: "Lazzari Mattia",               categoria: "U16", ruolo: "Centrocampista" },
  { nome: "Lazzarini Alex",               categoria: "U16", ruolo: "Centrocampista" },
  { nome: "Locuoco Marco",                categoria: "U16", ruolo: "Difensore"      },
  { nome: "Lubrano Lavadera Andrea",      categoria: "U16", ruolo: "Attaccante"     },
  { nome: "Marazzi Giorgio",              categoria: "U16", ruolo: "Centrocampista" },
  { nome: "Marchesetti Edoardo",          categoria: "U16", ruolo: "Centrocampista" },
  { nome: "Marchetti Riccardo",           categoria: "U16", ruolo: "Difensore"      },
  { nome: "Matrisciano Gabriel",          categoria: "U16", ruolo: "Centrocampista" },
  { nome: "Montini Leonardo",             categoria: "U16", ruolo: "Portiere"       },
  { nome: "Morgano Nicolò",               categoria: "U16", ruolo: "Centrocampista" },
  { nome: "Mozzi Riccardo Luigi",         categoria: "U16", ruolo: "Centrocampista" },
  { nome: "Musa Tommaso",                 categoria: "U16", ruolo: "Difensore"      },
  { nome: "Nguer Serigne Fallou",         categoria: "U16", ruolo: "Difensore"      },
  { nome: "Plebani Alberto",              categoria: "U16", ruolo: "Portiere"       },
  { nome: "Salvaderi Andrea",             categoria: "U16", ruolo: "Centrocampista" },
  { nome: "Sedassari Nicolò",             categoria: "U16", ruolo: "Centrocampista" },
  { nome: "Sgroia Sasha Alexander",       categoria: "U16", ruolo: "Attaccante"     },

  // U15
  { nome: "Annetta Alessandro",           categoria: "U15", ruolo: "Centrocampista" },
  { nome: "Bianchi Filippo",              categoria: "U15", ruolo: "Difensore"      },
  { nome: "Bonfiglio Marco",              categoria: "U15", ruolo: "Centrocampista" },
  { nome: "Boschiroli Roberto",           categoria: "U15", ruolo: "Centrocampista" },
  { nome: "Cavanna Filippo",              categoria: "U15", ruolo: "Attaccante"     },
  { nome: "Colombo Simone",               categoria: "U15", ruolo: "Difensore"      },
  { nome: "D'Antonio Francesco",          categoria: "U15", ruolo: "Attaccante"     },
  { nome: "DelBono Giovanni",             categoria: "U15", ruolo: "Attaccante"     },
  { nome: "Dieci Federico",               categoria: "U15", ruolo: "Difensore"      },
  { nome: "Emosti Marco",                 categoria: "U15", ruolo: "Centrocampista" },
  { nome: "Felini Mattia",                categoria: "U15", ruolo: "Centrocampista" },
  { nome: "Fiora Matteo",                 categoria: "U15", ruolo: "Attaccante"     },
  { nome: "Galoppini Davide",             categoria: "U15", ruolo: "Centrocampista" },
  { nome: "Ielmoni Jacopo",               categoria: "U15", ruolo: "Attaccante"     },
  { nome: "Lacerti Edoardo",              categoria: "U15", ruolo: "Centrocampista" },
  { nome: "Marchetti Cristian",           categoria: "U15", ruolo: "Difensore"      },
  { nome: "Moreschi Pietro",              categoria: "U15", ruolo: "Portiere"       },
  { nome: "Ndiaye Maguette",              categoria: "U15", ruolo: "Attaccante"     },
  { nome: "Oliverio Lorenzo",             categoria: "U15", ruolo: "Centrocampista" },
  { nome: "Perotti Sebastian",            categoria: "U15", ruolo: "Centrocampista" },
  { nome: "Pinotti Daniele",              categoria: "U15", ruolo: "Portiere"       },
  { nome: "Poggioli Pietro",              categoria: "U15", ruolo: "Difensore"      },
  { nome: "Poisetti Enrico",              categoria: "U15", ruolo: "Centrocampista" },
  { nome: "Rizzi Alberto",                categoria: "U15", ruolo: "Difensore"      },
  { nome: "Rusconi Davide",               categoria: "U15", ruolo: "Portiere"       },
  { nome: "Russo Achille",                categoria: "U15", ruolo: "Attaccante"     },
  { nome: "Scalvini Andrea",              categoria: "U15", ruolo: "Portiere"       },
  { nome: "Tiberti Nicholas",             categoria: "U15", ruolo: "Centrocampista" },
  { nome: "Torta Riccardo",               categoria: "U15", ruolo: "Attaccante"     },

  // U14
  { nome: "Anselmo Matteo",               categoria: "U14", ruolo: "Attaccante"     },
  { nome: "Bellini Mattia",               categoria: "U14", ruolo: "Centrocampista" },
  { nome: "Beltrame Luca",                categoria: "U14", ruolo: "Centrocampista" },
  { nome: "Benvenuti Luca",               categoria: "U14", ruolo: "Centrocampista" },
  { nome: "Bertoni Liam",                 categoria: "U14", ruolo: "Centrocampista" },
];
